FROM python:3.11.6
CMD ["python", "--version"]
WORKDIR /app
ARG RPI
ENV PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  POETRY_NO_INTERACTION=1 \
  POETRY_VIRTUALENVS_CREATE=false \
  POETRY_CACHE_DIR='/var/cache/pypoetry' \
  POETRY_HOME='/usr/local' \
  POETRY_VERSION=1.7.1

RUN pip install "poetry==$POETRY_VERSION"

COPY ./src/ ./src
COPY ./README.md .
COPY ./poetry.lock .
COPY ./pyproject.toml .
COPY docker/docker-poetry-install.sh .

RUN ./docker-poetry-install.sh --rpi $RPI

EXPOSE 8765

CMD ["/usr/bin/chrt", "-f", "90", "/usr/local/bin/poetry", "run", "--", "python", "-m", "src.main"]
